### ISSUE TITLE
Find grants

### ISSUE THREAD

**Issue by raykanani** [atj3097/level-1-dao#29]

**Comment by AL0YSI0US** [comment]
Projects looking great! Imma drop some links on y'all >> some resources I find handy . . . 

📌
            **G R A N T S** 💰

+ [**Polygon**](https://forum.polygon.technology/c/grants/11) "Polygon foundation will seed the Polygon Ecosystem DAO with $1 MN"
Read more [here](https://forum.polygon.technology/t/polygon-foundation-will-seed-the-polygon-ecosystem-dao-with-1-mn/328)

+ [**Gitcoin**](https://gitcoin.co/grants)

+ [**Hyperscale**](https://www.hyperscalefund.com/) Fast funding for web3 projects
Receive up to $1M by competing in the DAO Race. Join in 5 min and be voted on by the DAO. Takes 5 mins to fill out - get up to $1M in funding. 

+ [**Stacks Foundation Grant Program**](https://stacks.org/grants) “The Grants Program funds builders and developers who are creating developer tools, community resources, applications, and research that serve our mission of a user owned internet, powered by the Stacks Blockchain.”

+ [**web3.foundation**]( https://web3.foundation/grants/) “Our Grants Program offers recurring grants of up to $100k for public applications, which are tracked transparently on Github and disbursed in cryptocurrencies. Exceptions to these requirements and higher funding are also possible.”

+ [**Moonshot Collective**](https://moonshotcollective.space/) : Born from gitcoin I think…The Moonshot collective gathers once a month to receive new pitches. [dev stuff building out rad web3 ecosystem]

### cool stuff from the [moonshot collective](https://moonshotcollective.space/) : 
+ [tip.party](https://tip.party/)
+ [pay.party](https://pay.party/)
+ [scaffold-eth](https://github.com/scaffold-eth/scaffold-eth)

Something cool that [Juan Bell](https://twitter.com/Bellcho) recently shared with me : 
+ [Dework](https://dework.xyz/o/gravity-dao-4UHhckKWxf8whABj2pY8mV) - "Dework is a web3 project management tool that can execute the payment of bounties"

**Comment by raykanani** [comment]
Tracking some newly launched grant programs

- Olympus DAO grant
- Radical grants

**Comment by raykanani** [comment]
Created this board for us to track grant applications https://harmonious-bat-333.notion.site/Web3-Grants-for-Level1-e65297923bd24416b5a56c15d4249aa3 cc @atj3097

**Comment by raykanani** [comment]
Feels like we've found enough grants. Will close. Likely need to open an issue to start tracking applying to these
