### ISSUE TITLE
Create globally accessible user variable

### ISSUE THREAD

**Issue by raykanani** [atj3097/level-1-dao#40]
We need a way to check if the user is logged in and access user information if they are across the application.

My thinking is to have nav component be a global UI that shows up on every page. I'm not sure if this is the best way to do this though.

@faisalraza32 let me know if you have any thoughts

**Comment by faisalraza32** [comment]
@raykanani we have NavBar component and it shows on all pages and I have already added the auth0  **useUser** hook to check if a user is login or not.

The same hook can be used on any page to see if a user is logged in. 
We can also create user context to share the info in the app. I will take a look and will create one.

**Comment by raykanani** [comment]
Closed. Thank you @faisalraza32

**Comment by raykanani** [comment]
testing discord integration
