### ISSUE TITLE
username overwrites when a user logs in

### ISSUE THREAD

**Issue by raykanani** [atj3097/level-1-dao#64]
If you change your username, log-out and then log back in again, your username overwrites to the one from your log-in method.

This is reproducible when logging in with Google.

Expected behaviour, if username exists, it does not overwrite.

**Comment by faisalraza32** [comment]
We have Auth Pipeline rule "Create Hasura User", in the rule upsert user query was updating the username if the record already exists.

**Comment by raykanani** [comment]
Fixed :)
